/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal projects and is checked in here
// so TypeScript works before the first dev-server boot.
